Added ShoppingCart management
Bukozdem/book-shop pull request #8
Opened 2023-10-12 17:08 UTC by Bukozdem

2023-10-12 18:58 UTC, kerrrusha requested changes

2023-10-12 18:58 UTC, kerrrusha commented on src/main/java/book/online/model/CartItem.java
> +@Where(clause = "is_deleted=false")
The '@Where' annotation is used to add constraints to SQL statements, but here the clause 'is_deleted=false' may cause issues if 'is_deleted' is null. It is better to use 'is_deleted is false' to handle both cases where 'is_deleted' is false or null.

2023-10-12 18:58 UTC, kerrrusha commented on src/main/java/book/online/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(id).get();
Potential NoSuchElementException if findById(id) does not return a value. Please add orElseThrow() handling to avoid potential exceptions.

2023-10-12 18:58 UTC, kerrrusha commented on src/main/java/book/online/model/ShoppingCart.java
> +@Where(clause = "is_deleted=false")
The '@where' annotation is used to add constraints to SQL statements, but here the clause 'is_deleted=false' may cause issues if 'is_deleted' is null. It is better to use 'is_deleted is false' to handle both cases where 'is_deleted' is false or null.

2023-10-12 18:58 UTC, kerrrusha commented on src/main/java/book/online/model/ShoppingCart.java
> +    private User user;
should be not null

2023-10-13 08:39 UTC, Bukozdem commented on src/main/java/book/online/model/ShoppingCart.java
> +    private User user;
How do I add this property? 
If I use annotation @Column, I get an exception: not use '@Column' to specify column mappings (use '@PrimaryKeyJoinColumn' instead), but @PrimaryKeyJoinColumn doesn't have this property

2023-10-13 10:33 UTC, Rommelua commented on src/main/java/book/online/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
```

2023-10-15 09:01 UTC, merged